### ISSUE TITLE
[FEAT] 백엔드 API 요청 메서드 개발

### ISSUE THREAD

**Issue by JjungminLee** [yourssu/YLS-Web#16]
# ISSUE ✅ :  백엔드 API 요청 메서드 개발

## 📖 Summary
- 로컬 스토리지에 로그가 10개 쌓이면 백엔드에 put요청으로 쌓인 로그들을 보낸다.

**Comment by Hanna922** [comment]
그 저희가 하나의 도메인에서 10개 모여야만 보내는 게 아니라 전체 로깅에서 로그가 10개 모이면 보내는 구라 로컬 스토리지에 로그가 10개 쌓이는 걸로 보내면 쪼끔 결과가 달라지지 않을까 싶네용🤔🤔

**Comment by JjungminLee** [comment]
헉 근데 도메인에 상관없이 로컬스토리지에는 로그가 다 쌓일 수 있지 않을까요?! 흐음.. 한번 테스트 해봐야겠네영

**Comment by Hanna922** [comment]
엇 로컬 스토리지는 도메인별로 생성되는 걸로 알고있어요 ㅜ.ㅜ

**Comment by Hanna922** [comment]
엇 로컬 스토리지는 도메인별로 생성되는 걸로 알고있어요 ㅜ.ㅜ 다른 도메인의 로컬 스토리지에는 접근이 불가능해서 저희가 내부적으로 객체에 로그를 저장하고 있어야 할 것 같네용

**Comment by JjungminLee** [comment]
전역상태로 들고 있는건 너무 성능상 무리가 가는 행동이겠죠? ㅜㅜㅜ

**Comment by Hanna922** [comment]
엇 로그 자체는 로그인이랑 비로그인 상관이 없어서 내부 객체에 로그를 담아두고 길이가 10개가 되면 보내는 방식으로 구현하면 괜찮지 않을까용.......!? 전역 상태도 필요하진 않을 것 같은데 오음....아닐까요.....🤔

로그인, 비로그인 문제는 random string 생성 및 유지에만 해당되는 문제인 것 같아요!

**Comment by JjungminLee** [comment]
> 엇 로그 자체는 로그인이랑 비로그인 상관이 없어서 내부 객체에 로그를 담아두고 길이가 10개가 되면 보내는 방식으로 구현하면 괜찮지 않을까용.......!? 전역 상태도 필요하진 않을 것 같은데 오음....아닐까요.....🤔
> 
혹시 여기서 내부 객체가 뭔지 알 수 있을까요? 저는 10개가 모인다는게 하나의 로컬스토리지에 로그가 10개가 쌓였을때 보낸다는거였어요!

**Comment by JjungminLee** [comment]
> 로그인, 비로그인 문제는 random string 생성 및 유지에만 해당되는 문제인 것 같아요!
네넵! 회의 하면서 적다보니까 얘기하는거랑 쓰는게 섞여서 살짝 헷갈렸나봐요!

**Comment by JjungminLee** [comment]
> 
> 로그인, 비로그인 문제는 random string 생성 및 유지에만 해당되는 문제인 것 같아요!

네넵! 회의 하면서 적다보니까 얘기하는거랑 쓰는게 섞여서 살짝 헷갈렸나봐요!

**Comment by Hanna922** [comment]
여러 개의 도메인을 같이 관리하게 되면 특정 한 부분의 로컬 스토리지에 로그가 10개 쌓였을 때 보내는 방식이 YLS의 의도와는 다를 것 같아요..! 그래서 로그가 생성될 때 YLS 내부 객체에 로그를 모으고, 해당 객체의 길이가 10이 되었을 때 보내는게 적절하지 않을까 하는 얘기였습니당!

**Comment by JjungminLee** [comment]
아하 감사합니다! 그러면 이전 로컬스토리지 로직은 지울게요!  지금 막 생각나는게 없긴 한데요..! 그나마 내부객체로 계속 저장하는게 ContextAPI 가 어떨가 싶긴하네요 얘도 전역상태 느낌이긴한데 아까 숀님이 말씀해주신대로 하면 props drilling일어나지 않을까요오?!
