### ISSUE TITLE
[FEAT] 유저의 이탈했을때 로그를 백엔드에 보내기

### ISSUE THREAD

**Issue by JjungminLee** [yourssu/YLS-Web#21]
# ISSUE ✅ : 유저의 이탈했을때 로그를 백엔드에 보내기

## 📖 Summary
- 로그 개수와 상관없이 유저가 이탈했을 경우 로그를 백엔드에 보냅니다.

**Comment by Hanna922** [comment]
요거 '10개 미만일 경우' 조건은 추가하지 않아도 될 것 같아요!
이탈의 경우 무조건 쌓인 로그를 보내는 게 좋을 것 같다고 저번에 얘기 나눴던 것 같아서용
